# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0397898a19bd51c6a50961473609abc27acac68cfea6c3f6eb24b9e2a8a448fdd49b8c2d4b79cf9cc6a99eab5ff289410633ca429492724c72fca4d29e26676e

test:
  secret_key_base: 4f49b8d6c49e9c2430da3670b51bfcc78b2252c99368d6808b7837095ddc89b88efbc588b11bb52fa10bf6a5c70d7965c81f55e65156c03f7f90243b328ddf62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
